    deletionPolicy:
    forProvider:
        addonsConfig:
            cloudRunConfig:
                disabled:
                loadBalancerType:
            configConnectorConfig:
                enabled:
            dnsCacheConfig:
                enabled:
            gcePersistentDiskCSIDriverConfig:
                enabled:
            horizontalPodAutoscaling:
                disabled:
            httpLoadBalancing:
                disabled:
            kubernetesDashboard:
                disabled:
            networkPolicyConfig:
                disabled:
        authenticatorGroupsConfig:
            enabled:
            securityGroup:
        autopilot:
            enabled:
        autoscaling:
            autoprovisioningLocations:
            autoprovisioningNodePoolDefaults:
                bootDiskKmsKey:
                diskSizeGb:
                diskType:
                management:
                    autoRepair:
                    autoUpgrade:
                minCpuPlatform:
                oauthScopes:
                serviceAccount:
                shieldedInstanceConfig:
                    enableIntegrityMonitoring:
                    enableSecureBoot:
                upgradeSettings:
                    maxSurge:
                    maxUnavailable:
                enableNodeAutoprovisioning:
                resourceLimits:
                    maximum: 
                    minimum: 
                    resourceType:
        binaryAuthorization:
                    enabled:
        clusterIpv4Cidr:
        confidentialNodes:
                enabled:
        databaseEncryption:
                keyname:
                state:
        defaultMaxPodsConstraint:
                maxPodsPerNode:
        description:
        enableKubernetesAlpha:
        enableTpu:
        initialClusterVersion:
        ipAllocationPolicy:
            clusterIpv4CidrBlock:
            clusterSecondaryRangeName:
            createSubnetwork:
            nodeIpv4CidrBlock:
            servicesIpv4CidrBlock:
            servicesSecondaryRangeName:
            subnetworkName:
            tpuIpv4CidrBlock: 
            useIPAliases:
            useRoutes:
        labelFingerprint:
        legacyAbac:
            enabled:
        location:
        locations:
        loggingService:
        maintenancePolicy:
            window:
                dailyMaintenanceWindow:
                    startTime:
                maintenanceExclusions:
                recurringWindow:
                    recurrence:
                    window:
                        endTime:
                        startTime:
        masterAuth:
            clientCertificateConfig:
                    issueClientCertificate:
            username:
        masterAuthorizedNetworksConfig:
            cidrBlocks:
                - cidrBlock:
                  displayName:
            enabled:
        monitoringService:
        network:
        networkConfig: 
            datapathProvider:
            defaultSnatStatus:
                disabled:
            enableIntraNodeVisibility:
            privateIpv6GoogleAccess:
        networkPolicy:
                enabled:
                provider:
        networkRef:
                    name:
        networkSelector:
                matchControllerRef:
                matchLabels:
        notificationConfig: 
                    pubsub: 
                        enabled:
                        topic:
        privateClusterConfig:
                enablePrivateEndpoint:
                enablePrivateNodes:
                masterGlobalAccessConfig: 
                    enabled:
                masterIpv4CidrBlock:
        releaseChannel:
                channel:
        resourceLabels:
        resourceUsageExportConfig:
                bigqueryDestination:
                    datasetId:
                consumptionMeteringConfig:
                enableNetworkEgressMetering:
        subnetwork:
        subnetworkRef:
                name:
        subnetworkSelector:
                matchControllerRef:
                matchLabels:
        verticalPodAutoscaling:
                enabled:
        workloadIdentityConfig:
                workloadPool:
    providerConfigRef:
        name:
    providerRef:
        name:
