nameOverride: "gcp-alphasense"
project_id: "searce-academy"
env: "prod"
providerConfigRef: "default"
vpc:
  deletion_policy: "Delete" #Delete/Orphan
  providerspec:
      autoCreateSubnet: false
      routingMode: "GLOBAL"
  providerConfigRef: "default"
subnet:
  providerConfigRef: "default"
  deletion_policy: "Delete" #Delete/Orphan
  providerspec:
    enableFlowLogs: false
  regions:
    - region: "us-west1"
      ipaddress: "10.0.0.0/16"
      secondaryRanges:
        - iprange: "10.0.1.0/16"
          name: "pod-ip-range"
        - iprange: "10.0.2.0/16"
          name: "services-ip-range"
#    - region: "us-west2"
#      ipaddress: "10.1.0.0/16"
#    - region: "us-north1"
#      ipaddress: "10.2.0.0/16"
#    - region: "us-east1"
#      ipaddress: "10.3.0.0/16"
router:
  providerConfigRef: "default"
  deletion_policy: "Delete"
  providerspec:
    region: "us-west1"
    description: "test"
    #network: "projects/{{ $.Values.project_id}}/global/networks/{{ $.Values.env}}-vpc"

    bgp:
      advertiseMode: "CUSTOM"
      advertisedGroups: ["ALL_SUBNETS"]
      advertisedIpRanges:
        - description: "test range"
          range: "10.7.0.0/16"
        - description: "test range2"
          range: "10.8.0.0/16"
         
        
      asn:
    bgpPeers:
      advertiseMode: 
      advertisedGroups:
      advertisedIpRanges:
        description:
        range: 
      advertisedRoutePriority:
      interfaceName:
      ipAddress:
      name:
      peerAsn:
      peerIpAddress:
value_cm: 